local Plot = require("plot.plot")

PlotCutscene = {
	PlayRate = 1,
	config = {
		isLooping = false,
		isSkippable = true,
		independentMusic = false,
		hideUI = true,
		hideCharacter = true,
		showBorder = true,
		showCurtain = true,
		fadeInOutTime = 0.7,
		mainCameraControl = true,
		previewMode = false,
	},
	StartTime = 0,
	Duration = 5,
	CurrentState = 5,
	AssetIndexList = {
		[1] = "linsangniang",
		[2] = "yinghua",
		[3] = "lsntx",
	},
	Title = "caomiao_boss_2",
	EndTime = 5,
	Type = "PlotDirector.PlotCutscene",
	ParentId = -1,
	PlotElements = {
		[1] = {
			IndexName = "yinghua",
			Active = true,
			SetParent = false,
			ParentName = "",
			SetTrans = true,
			Position = Vector3(425.07,6.94,45.92843),
			Rotation = Vector3(0,1.126611,0),
			LocalScale = Vector3(1,1,1),
			ObjectName = "yinghua",
			StartTime = 0,
			Duration = 1,
			CurrentState = 5,
			Title = "object_create",
			EndTime = 1,
			Type = "PlotDirector.PlotEventObjectCreate",
			ParentId = 5,
		},
		[2] = {
			AudioMode = "Sound2D",
			LoadMode = "Delay",
			IndexName = "cg_gunzou",
			Looping = false,
			StartPlayPos = 0,
			EndPlayPos = 4.107914,
			Is3DSound = false,
			Position = Vector3(0,0,0),
			VolumeControl = "Default",
			VolumeValue = 1,
			VolumeCurve = {
				Name = "",
				KeyList = {},
			},
			StartTime = 0,
			Duration = 4.107914,
			CurrentState = 5,
			Title = "back_sound",
			EndTime = 4.107914,
			Type = "PlotDirector.PlotEventBackSound",
			ParentId = 6,
		},
		[3] = {
			ProfessionDeviation = false,
			PathMode = "Bessel",
			TangentMode = false,
			PositionVary = true,
			RotationVary = true,
			ScaleVary = true,
			ConstSpeed = false,
			Speed = 7,
			PathList = {
				[1] = {
					NodeTime = 0,
					Position = Vector3(422.7513,20.85229,50.91775),
					Rotation = Vector3(1.754482,180.5852,7.697576E-06),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(422.7513,20.85229,50.91775),
					OutTangent = Vector3(422.7513,20.85229,50.91775),
				},
				[2] = {
					NodeTime = 2,
					Position = Vector3(422.8125,20.28684,49.16812),
					Rotation = Vector3(13.78646,178.5226,8.475073E-06),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(422.8125,20.28684,49.16812),
					OutTangent = Vector3(422.8125,20.28684,49.16812),
				},
			},
			StartTime = 0,
			Duration = 2,
			CurrentState = 5,
			Title = "path",
			EndTime = 2,
			Type = "PlotDirector.PlotEventCameraPath",
			ParentId = 2,
		},
		[4] = {
			IndexName = "linsangniang",
			Active = true,
			SetParent = false,
			ParentName = "",
			SetTrans = true,
			Position = Vector3(422.76,18.94,40.55),
			Rotation = Vector3(0,1.126611,0),
			LocalScale = Vector3(1,1,1),
			ObjectName = "sanniang",
			StartTime = 0,
			Duration = 0.2,
			CurrentState = 5,
			Title = "object_create",
			EndTime = 0.2,
			Type = "PlotDirector.PlotEventObjectCreate",
			ParentId = 3,
		},
		[5] = {
			ObjectName = "sanniang",
			IsLoop = false,
			StateName = "walk",
			Layer = -1,
			NormalizedTime = 0,
			IsCrossFade = false,
			TransitionDuration = 0,
			StartTime = 0.2,
			Duration = 1.066667,
			CurrentState = 5,
			Title = "animator_play",
			EndTime = 1.266667,
			Type = "PlotDirector.PlotEventAnimatorPlay",
			ParentId = 3,
		},
		[6] = {
			ObjectName = "sanniang",
			OnGround = true,
			OffSetY = 0,
			PathMode = "Bessel",
			TangentMode = false,
			PositionVary = true,
			RotationVary = true,
			ScaleVary = true,
			ConstSpeed = false,
			Speed = 7,
			PathList = {
				[1] = {
					NodeTime = 0,
					Position = Vector3(422.76,18.94,40.55),
					Rotation = Vector3(0,1.126611,0),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(422.76,18.94,40.55),
					OutTangent = Vector3(422.76,18.94,40.55),
				},
				[2] = {
					NodeTime = 2.5,
					Position = Vector3(422.762,18.05,43.9),
					Rotation = Vector3(0,1.126611,0),
					LocalScale = Vector3(1,1,1),
					InTangent = Vector3(422.762,18.05,43.9),
					OutTangent = Vector3(422.762,18.05,43.9),
				},
			},
			StartTime = 0.2,
			Duration = 2.5,
			CurrentState = 5,
			Title = "object_path",
			EndTime = 2.7,
			Type = "PlotDirector.PlotEventObjectPath",
			ParentId = 4,
		},
		[7] = {
			AudioMode = "Sound2D",
			LoadMode = "Delay",
			IndexName = "wpn_magic_shot_01",
			Looping = false,
			StartPlayPos = 0,
			EndPlayPos = 2.707218,
			Is3DSound = false,
			Position = Vector3(0,0,0),
			VolumeControl = "Curve",
			VolumeValue = 1,
			VolumeCurve = {
				Name = "",
				KeyList = {
					[1] = UnityEngine.Keyframe(0,1,0,0),
					[2] = UnityEngine.Keyframe(1.885663,1,0,0),
					[3] = UnityEngine.Keyframe(2.707218,0,0,0),
				},
			},
			StartTime = 2.292782,
			Duration = 2.707218,
			CurrentState = 5,
			Title = "back_sound",
			EndTime = 5,
			Type = "PlotDirector.PlotEventBackSound",
			ParentId = 7,
		},
		[8] = {
			ObjectName = "sanniang",
			SpeedValue = 0.5,
			Curve = {
				Name = "",
				KeyList = {},
			},
			StartTime = 2.7,
			Duration = 2.3,
			CurrentState = 4,
			Mode = "Event",
			Title = "animator_speed",
			EndTime = 5,
			Type = "PlotDirector.PlotEventAnimatorSpeed",
			ParentId = 4,
		},
		[9] = {
			ObjectName = "sanniang",
			IsLoop = false,
			StateName = "skill01",
			Layer = -1,
			NormalizedTime = 0,
			IsCrossFade = false,
			TransitionDuration = 0,
			StartTime = 2.7,
			Duration = 2.333333,
			CurrentState = 5,
			Title = "animator_play",
			EndTime = 5.033334,
			Type = "PlotDirector.PlotEventAnimatorPlay",
			ParentId = 3,
		},
		[10] = {
			IndexName = "lsntx",
			Active = true,
			SetParent = false,
			ParentName = "",
			SetTrans = true,
			Position = Vector3(422.762,18.93,43.9),
			Rotation = Vector3(0,1.126611,0),
			LocalScale = Vector3(1,1,1),
			ObjectName = "lsntx",
			StartTime = 2.75,
			Duration = 1,
			CurrentState = 5,
			Title = "object_create",
			EndTime = 3.75,
			Type = "PlotDirector.PlotEventObjectCreate",
			ParentId = 5,
		},
		[11] = {
			AudioMode = "Sound2D",
			LoadMode = "Delay",
			IndexName = "skill_common_cure_02",
			Looping = false,
			StartPlayPos = 0,
			EndPlayPos = 1.444308,
			Is3DSound = false,
			Position = Vector3(0,0,0),
			VolumeControl = "Default",
			VolumeValue = 1,
			VolumeCurve = {
				Name = "",
				KeyList = {},
			},
			StartTime = 3.555692,
			Duration = 1.444308,
			CurrentState = 5,
			Title = "back_sound",
			EndTime = 5,
			Type = "PlotDirector.PlotEventBackSound",
			ParentId = 8,
		},
	},
}
setmetatable(PlotCutscene, {__index = Plot.PlotCutscene})
return PlotCutscene