local Plot = require("plot.plot")

PlotCutscene = {
	PlayRate = 1,
	config = {
		isLooping = false,
		isSkippable = true,
		independentMusic = true,
		hideUI = true,
		hideCharacter = true,
		showBorder = true,
		showCurtain = true,
		fadeInOutTime = 0.7,
		mainCameraControl = true,
		previewMode = false,
	},
	StartTime = 0,
	Duration = 10,
	CurrentState = 5,
	AssetIndexList = {
		[1] = "biyao",
	},
	Title = "plotcutscene",
	EndTime = 10,
	Type = "PlotDirector.PlotCutscene",
	ParentId = -1,
	PlotElements = {
		[1] = {
			IndexName = "biyao",
			Active = true,
			SetParent = false,
			ParentName = "",
			SetTrans = true,
			Position = Vector3(0,0,0),
			Rotation = Vector3(0,0,0),
			LocalScale = Vector3(1,1,1),
			ObjectName = "df",
			StartTime = 0,
			Duration = 1,
			CurrentState = 5,
			Title = "object_create",
			EndTime = 1,
			Type = "PlotDirector.PlotEventObjectCreate",
			ParentId = 3,
		},
		[2] = {
			ObjectName = "df/Bip001/Bip001 Pelvis",
			Active = false,
			StartTime = 1,
			Duration = 1,
			CurrentState = 5,
			Title = "object_show_hide",
			EndTime = 2,
			Type = "PlotDirector.PlotEventObjectShowHide",
			ParentId = 3,
		},
		[3] = {
			ObjectName = "df/Bip001/Bip001 Pelvis",
			Active = true,
			StartTime = 7.040001,
			Duration = 1,
			CurrentState = 5,
			Title = "object_show_hide",
			EndTime = 8.040001,
			Type = "PlotDirector.PlotEventObjectShowHide",
			ParentId = 3,
		},
	},
}
setmetatable(PlotCutscene, {__index = Plot.PlotCutscene})
return PlotCutscene