---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hadow.
--- DateTime: 2020/2/15 21:20
---

local UIManager = require("uimanager")

local Anchor_Widgets = {}

local function FindAllWidget(fields)

    --Anchor_Widgets["TopLeft"] = fields.TweenPosition_Left.transform:GetComponent("UIWidget")
    --Anchor_Widgets["TopRight"] = fields.TweenPosition_Top.transform:GetComponent("UIWidget")
    Anchor_Widgets["Center"] = fields.UITexture_Main
end


local function ResetWidget(fields)
    FindAllWidget(fields)
    for pivot, widget in pairs(Anchor_Widgets) do
        UIManager.SetAnchor(widget)
    end
end


return {
    ResetWidget = ResetWidget,
}