---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hadow.
--- DateTime: 2020/3/5 14:59
---

local gameevent = require "gameevent"
local uimanager = require"uimanager"
local www

local url

local timeout =3
local elapsedTime


local eventid
local retry

local avatartexture

local function StopUpdate()

    if eventid then
        gameevent.evt_late_update:remove(eventid)
        eventid = nil
    end
end

local function DestroyWWW()
    if www then
        www:Dispose()
        www = nil
    end
end

local function Retry()

    DestroyWWW()
    retry = retry -1
    elapsedTime = 0

    if retry == 0 then
        --StopUpdate()
        StopUpdate()
    end
end

local function late_update()


    if url == nil then
        url = GetHeadAvatarUrl()
    end


    if not avatartexture and elapsedTime < timeout then

        elapsedTime = elapsedTime + Time.deltaTime;

        if www then
            if www.isDone then
                if IsNull(www.error) then
                    avatartexture = www.texture

                    if avatartexture then

                        if uimanager.isshow("dlguimain_roleinfo") then
                            uimanager.call("dlguimain_roleinfo","RefreshRoleInfo")
                        end
                        StopUpdate()
                    end
                else

                    if retry > 0 then
                        Retry()
                    end
                end

            end
        else
            www = WWW(url)
        end

    else

        if retry > 0 then
            Retry()
        end
    end

end






local function getavatar()
    return avatartexture
end

local function init()

    www = nil
    eventid = nil
    elapsedTime = 0
    retry = 3
    eventid = gameevent.evt_late_update:add(late_update)
    url = GetHeadAvatarUrl()
end

return{
    init = init,
    getavatar = getavatar,
}